name 'mthibaut-archive'
version '1.0.1'
author 'mthibaut'
license 'Apache License, Version 2.0'
summary 'Ensure archive creation or extraction.'
description 'Ensures that an archive can be extracted automatically, or created automatically using puppet. Currently only a tar provider exists, but others can be written.'
